llm:
  provider: "openai"
  model: "gpt-4-turbo"
  api_key: "YOUR_OPENAI_API_KEY" # Use environment variables in production

retriever:
  dense:
    model: "sentence-transformers/all-MiniLM-L6-v2"
    index_path: "storage/faiss_index"
  sparse:
    host: "localhost"
    port: 9200
    index_name: "documents"
  hybrid:
    reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    alpha: 0.5 # Weight for dense vs. sparse scores

tools:
  calculator:
    enabled: true
  web_search:
    enabled: true
    api_key: "YOUR_SEARCH_API_KEY"
  database:
    enabled: false
    connection_string: "sqlite:///mydatabase.db"

logging:
  level: "INFO"
  file: "logs/agentic_rag.log"

memory:
  working_memory_capacity: 10
  episodic_log_path: "storage/episodic_memory.log"

bias:
  sycophancy_factor: 0.5
  confirmation_bias_strength: 0.5